# -*- coding: utf-8 -*-
"""data_analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19GciZIFko72Tit42v0_olsuki4UoOnfR
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/Crypto.csv')
df.head()

print("Shape of the DataFrame:", df.shape)

print("Data types:\n", df.dtypes)

print("Missing values:\n", df.isnull().sum())

#Top Cryptocurrencies by Market Cap

df['marketcap'] = pd.to_numeric(df['marketcap'], errors='coerce')
top_crypto = df.groupby('name')['marketcap'].sum().sort_values(ascending=False).head(10)
plt.figure(figsize=(12, 6))
top_crypto.plot(kind='bar', color='skyblue')
plt.title('Top 10 Cryptocurrencies by Market Capitalization')
plt.ylabel('Market Cap (in billions)')
plt.xlabel('Cryptocurrency')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

#Price Distribution
plt.figure(figsize=(10,6))
sns.histplot(df['price'], bins=50, kde=True)
plt.title('Distribution of Cryptocurrency Prices')
plt.xlabel('Price (USD)')
plt.ylabel('Frequency')
plt.xscale('log')
plt.show()

#Volume vs. Market Cap Analysis
plt.figure(figsize=(10,6))
sns.scatterplot(x='marketcap', y='volume24hrs', data=df, alpha=0.6)
plt.title('24hr Trading Volume vs Market Capitalization')
plt.xlabel('Market Cap (log scale)')
plt.ylabel('24hr Volume (log scale)')
plt.xscale('log')
plt.yscale('log')
plt.show()

#Correlation Analysis
numerical_cols = ['price', 'volume24hrs', 'marketcap', 'circulatingsupply', 'maxsupply', 'totalsupply']
corr_matrix = df[numerical_cols].corr()

plt.figure(figsize=(10,8))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', center=0)
plt.title('Correlation Matrix of Cryptocurrency Metrics')
plt.show()

#Price volatility analysis
volatility = df.groupby('name')['price'].std().sort_values(ascending=False).head(10)
plt.figure(figsize=(12,6))
volatility.plot(kind='bar', color='orange')
plt.title('Top 10 Most Volatile Cryptocurrencies (by Price Standard Deviation)')
plt.ylabel('Price Standard Deviation')
plt.xlabel('Cryptocurrency')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

#Price Trend of a Specific Crypto Over Time
btc = df[df['abbr'] == 'BTC']
btc.plot(x='date_taken', y='price', title='Bitcoin Price Over Time', figsize=(10,5))
plt.ylabel('Price ($)')
plt.show()